service: airkeeper

package:
  patterns:
    - ./config/airkeeper.json
    - '!src'
    - '!.*'

provider:
  name: aws
  region: ${opt:region, env:REGION, 'us-east-1'}
  stage: ${opt:stage, env:STAGE, 'dev'}
  runtime: nodejs14.x
  memorySize: 512
  logRetentionInDays: 14
  environment: ${file(scripts/load-secrets-env.js)}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: !Sub 'arn:aws:lambda:${self:provider.region}:${AWS::AccountId}:function:${self:service}-${self:provider.stage}-process-subscriptions'

functions:
  rrp-beacon-update:
    handler: dist/handlers/rrp.handler
    timeout: 60
    events:
      - schedule: rate(1 minute)
    reservedConcurrency: 1
  psp-beacon-update:
    handler: dist/handlers/psp.handler
    environment:
      CLOUD_PROVIDER: ${param:provider, self:provider.name}
      STAGE: ${self:provider.stage}
    timeout: 60
    events:
      - schedule: rate(1 minute)
    reservedConcurrency: 1
  process-subscriptions:
    handler: dist/handlers/process-subscriptions.handler
    timeout: 15
    reservedConcurrency: 100
